name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - numpy
  - pandas
  - xarray
  - joblib
  - matplotlib
  - seaborn
  - plotly
  - scipy
  - statsmodels
  - scikit-learn
  - tensorflow
  - keras
  - keras-tuner
  - pyyaml
  - tqdm
  - pillow
  - pip
  - pip:
      - ipython  # For IPython display
